# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(1280, 650)
        window.setMinimumSize(QtCore.QSize(1280, 650))
        window.setMaximumSize(QtCore.QSize(1280, 650))
        window.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        window.setMouseTracking(False)
        window.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.work_plane = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.work_plane.setGeometry(QtCore.QRect(50, 0, 1231, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.work_plane.sizePolicy().hasHeightForWidth())
        self.work_plane.setSizePolicy(sizePolicy)
        self.work_plane.setMouseTracking(True)
        self.work_plane.setAutoFillBackground(True)
        self.work_plane.setObjectName("work_plane")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 44, 471))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.Instruments = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.Instruments.setContentsMargins(0, 0, 0, 0)
        self.Instruments.setSpacing(0)
        self.Instruments.setObjectName("Instruments")
        self.point = QtWidgets.QPushButton(self.layoutWidget_2)
        self.point.setEnabled(True)
        self.point.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/point.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.point.setIcon(icon)
        self.point.setIconSize(QtCore.QSize(30, 30))
        self.point.setCheckable(True)
        self.point.setChecked(False)
        self.point.setAutoRepeat(True)
        self.point.setObjectName("point")
        self.Instruments.addWidget(self.point)
        self.line = QtWidgets.QPushButton(self.layoutWidget_2)
        self.line.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.line.setIcon(icon1)
        self.line.setIconSize(QtCore.QSize(30, 30))
        self.line.setCheckable(True)
        self.line.setAutoRepeat(True)
        self.line.setObjectName("line")
        self.Instruments.addWidget(self.line)
        self.combine_points = QtWidgets.QPushButton(self.layoutWidget_2)
        self.combine_points.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/combine_points.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combine_points.setIcon(icon2)
        self.combine_points.setIconSize(QtCore.QSize(30, 30))
        self.combine_points.setCheckable(True)
        self.combine_points.setAutoRepeat(True)
        self.combine_points.setObjectName("combine_points")
        self.Instruments.addWidget(self.combine_points)
        self.point_on_middle_line = QtWidgets.QPushButton(self.layoutWidget_2)
        self.point_on_middle_line.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/point_on_middle_line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.point_on_middle_line.setIcon(icon3)
        self.point_on_middle_line.setIconSize(QtCore.QSize(30, 30))
        self.point_on_middle_line.setCheckable(True)
        self.point_on_middle_line.setAutoRepeat(True)
        self.point_on_middle_line.setObjectName("point_on_middle_line")
        self.Instruments.addWidget(self.point_on_middle_line)
        self.point_on_line = QtWidgets.QPushButton(self.layoutWidget_2)
        self.point_on_line.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/point_on_line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.point_on_line.setIcon(icon4)
        self.point_on_line.setIconSize(QtCore.QSize(30, 30))
        self.point_on_line.setCheckable(True)
        self.point_on_line.setAutoRepeat(True)
        self.point_on_line.setObjectName("point_on_line")
        self.Instruments.addWidget(self.point_on_line)
        self.parallelism = QtWidgets.QPushButton(self.layoutWidget_2)
        self.parallelism.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/parallelism.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.parallelism.setIcon(icon5)
        self.parallelism.setIconSize(QtCore.QSize(30, 30))
        self.parallelism.setCheckable(True)
        self.parallelism.setAutoRepeat(True)
        self.parallelism.setObjectName("parallelism")
        self.Instruments.addWidget(self.parallelism)
        self.normal = QtWidgets.QPushButton(self.layoutWidget_2)
        self.normal.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/normal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.normal.setIcon(icon6)
        self.normal.setIconSize(QtCore.QSize(30, 30))
        self.normal.setCheckable(True)
        self.normal.setAutoRepeat(True)
        self.normal.setObjectName("normal")
        self.Instruments.addWidget(self.normal)
        self.horizontally = QtWidgets.QPushButton(self.layoutWidget_2)
        self.horizontally.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resources/horizontally.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.horizontally.setIcon(icon7)
        self.horizontally.setIconSize(QtCore.QSize(30, 30))
        self.horizontally.setCheckable(True)
        self.horizontally.setAutoRepeat(True)
        self.horizontally.setObjectName("horizontally")
        self.Instruments.addWidget(self.horizontally)
        self.fix_size = QtWidgets.QPushButton(self.layoutWidget_2)
        self.fix_size.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resources/fix_size.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fix_size.setIcon(icon8)
        self.fix_size.setIconSize(QtCore.QSize(30, 30))
        self.fix_size.setCheckable(True)
        self.fix_size.setAutoRepeat(True)
        self.fix_size.setObjectName("fix_size")
        self.Instruments.addWidget(self.fix_size)
        self.fix_point = QtWidgets.QPushButton(self.layoutWidget_2)
        self.fix_point.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resources/fix_point.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fix_point.setIcon(icon9)
        self.fix_point.setIconSize(QtCore.QSize(30, 30))
        self.fix_point.setCheckable(True)
        self.fix_point.setAutoRepeat(True)
        self.fix_point.setObjectName("fix_point")
        self.Instruments.addWidget(self.fix_point)
        self.fix_length = QtWidgets.QPushButton(self.layoutWidget_2)
        self.fix_length.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resources/fix_length.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fix_length.setIcon(icon10)
        self.fix_length.setIconSize(QtCore.QSize(30, 30))
        self.fix_length.setCheckable(True)
        self.fix_length.setAutoRepeat(True)
        self.fix_length.setObjectName("fix_length")
        self.Instruments.addWidget(self.fix_length)
        self.fix_angle = QtWidgets.QPushButton(self.layoutWidget_2)
        self.fix_angle.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.fix_angle.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("resources/fix_angle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fix_angle.setIcon(icon11)
        self.fix_angle.setIconSize(QtCore.QSize(30, 30))
        self.fix_angle.setCheckable(True)
        self.fix_angle.setAutoRepeat(True)
        self.fix_angle.setObjectName("fix_angle")
        self.Instruments.addWidget(self.fix_angle)
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setEnabled(True)
        self.listView.setGeometry(QtCore.QRect(50, 0, 256, 581))
        self.listView.setAutoFillBackground(False)
        self.listView.setObjectName("listView")
        self.point_widget = QtWidgets.QWidget(self.centralwidget)
        self.point_widget.setGeometry(QtCore.QRect(50, 580, 281, 31))
        self.point_widget.setAutoFillBackground(True)
        self.point_widget.setObjectName("point_widget")
        self.point_y = QtWidgets.QDoubleSpinBox(self.point_widget)
        self.point_y.setGeometry(QtCore.QRect(130, 0, 69, 26))
        self.point_y.setObjectName("point_y")
        self.point_x = QtWidgets.QDoubleSpinBox(self.point_widget)
        self.point_x.setGeometry(QtCore.QRect(30, 0, 69, 26))
        self.point_x.setObjectName("point_x")
        self.label = QtWidgets.QLabel(self.point_widget)
        self.label.setGeometry(QtCore.QRect(10, -10, 20, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.point_widget)
        self.label_2.setGeometry(QtCore.QRect(110, -10, 20, 41))
        self.label_2.setObjectName("label_2")
        self.point_submit = QtWidgets.QPushButton(self.point_widget)
        self.point_submit.setGeometry(QtCore.QRect(210, 0, 61, 25))
        self.point_submit.setObjectName("point_submit")
        self.footer_widget = QtWidgets.QWidget(self.centralwidget)
        self.footer_widget.setGeometry(QtCore.QRect(50, 580, 1231, 31))
        self.footer_widget.setAutoFillBackground(True)
        self.footer_widget.setObjectName("footer_widget")
        self.line_widget = QtWidgets.QWidget(self.centralwidget)
        self.line_widget.setGeometry(QtCore.QRect(50, 580, 521, 31))
        self.line_widget.setAutoFillBackground(True)
        self.line_widget.setObjectName("line_widget")
        self.line_y_1 = QtWidgets.QDoubleSpinBox(self.line_widget)
        self.line_y_1.setGeometry(QtCore.QRect(150, 0, 69, 26))
        self.line_y_1.setObjectName("line_y_1")
        self.line_x_1 = QtWidgets.QDoubleSpinBox(self.line_widget)
        self.line_x_1.setGeometry(QtCore.QRect(40, 0, 69, 26))
        self.line_x_1.setObjectName("line_x_1")
        self.label_9 = QtWidgets.QLabel(self.line_widget)
        self.label_9.setGeometry(QtCore.QRect(10, -10, 20, 41))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.line_widget)
        self.label_10.setGeometry(QtCore.QRect(120, -10, 20, 41))
        self.label_10.setObjectName("label_10")
        self.line_submit = QtWidgets.QPushButton(self.line_widget)
        self.line_submit.setGeometry(QtCore.QRect(460, 0, 61, 25))
        self.line_submit.setObjectName("line_submit")
        self.label_11 = QtWidgets.QLabel(self.line_widget)
        self.label_11.setGeometry(QtCore.QRect(230, -10, 20, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.line_widget)
        self.label_12.setGeometry(QtCore.QRect(340, -10, 20, 41))
        self.label_12.setObjectName("label_12")
        self.line_x_2 = QtWidgets.QDoubleSpinBox(self.line_widget)
        self.line_x_2.setGeometry(QtCore.QRect(260, 0, 69, 26))
        self.line_x_2.setObjectName("line_x_2")
        self.line_y_2 = QtWidgets.QDoubleSpinBox(self.line_widget)
        self.line_y_2.setGeometry(QtCore.QRect(370, 0, 69, 26))
        self.line_y_2.setObjectName("line_y_2")
        self.combine_points_widget = QtWidgets.QWidget(self.centralwidget)
        self.combine_points_widget.setGeometry(QtCore.QRect(50, 580, 241, 31))
        self.combine_points_widget.setAutoFillBackground(True)
        self.combine_points_widget.setObjectName("combine_points_widget")
        self.combine_points_submit = QtWidgets.QPushButton(self.combine_points_widget)
        self.combine_points_submit.setGeometry(QtCore.QRect(170, 0, 61, 25))
        self.combine_points_submit.setObjectName("combine_points_submit")
        self.combine_points_point_1 = QtWidgets.QCheckBox(self.combine_points_widget)
        self.combine_points_point_1.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.combine_points_point_1.setCheckable(False)
        self.combine_points_point_1.setObjectName("combine_points_point_1")
        self.combine_points_point_2 = QtWidgets.QCheckBox(self.combine_points_widget)
        self.combine_points_point_2.setGeometry(QtCore.QRect(90, 0, 92, 23))
        self.combine_points_point_2.setCheckable(False)
        self.combine_points_point_2.setObjectName("combine_points_point_2")
        self.point_on_middle_line_widget = QtWidgets.QWidget(self.centralwidget)
        self.point_on_middle_line_widget.setGeometry(QtCore.QRect(50, 580, 241, 31))
        self.point_on_middle_line_widget.setAutoFillBackground(True)
        self.point_on_middle_line_widget.setObjectName("point_on_middle_line_widget")
        self.point_on_middle_line_submit = QtWidgets.QPushButton(self.point_on_middle_line_widget)
        self.point_on_middle_line_submit.setGeometry(QtCore.QRect(170, 0, 61, 25))
        self.point_on_middle_line_submit.setObjectName("point_on_middle_line_submit")
        self.point_on_middle_line_point = QtWidgets.QCheckBox(self.point_on_middle_line_widget)
        self.point_on_middle_line_point.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.point_on_middle_line_point.setCheckable(False)
        self.point_on_middle_line_point.setObjectName("point_on_middle_line_point")
        self.point_on_middle_line_line = QtWidgets.QCheckBox(self.point_on_middle_line_widget)
        self.point_on_middle_line_line.setGeometry(QtCore.QRect(90, 0, 92, 23))
        self.point_on_middle_line_line.setCheckable(False)
        self.point_on_middle_line_line.setObjectName("point_on_middle_line_line")
        self.point_on_line_widget = QtWidgets.QWidget(self.centralwidget)
        self.point_on_line_widget.setGeometry(QtCore.QRect(50, 580, 241, 31))
        self.point_on_line_widget.setAutoFillBackground(True)
        self.point_on_line_widget.setObjectName("point_on_line_widget")
        self.point_on_line_submit = QtWidgets.QPushButton(self.point_on_line_widget)
        self.point_on_line_submit.setGeometry(QtCore.QRect(170, 0, 61, 25))
        self.point_on_line_submit.setObjectName("point_on_line_submit")
        self.point_on_line_point = QtWidgets.QCheckBox(self.point_on_line_widget)
        self.point_on_line_point.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.point_on_line_point.setCheckable(False)
        self.point_on_line_point.setObjectName("point_on_line_point")
        self.point_on_line_line = QtWidgets.QCheckBox(self.point_on_line_widget)
        self.point_on_line_line.setGeometry(QtCore.QRect(90, 0, 92, 23))
        self.point_on_line_line.setCheckable(False)
        self.point_on_line_line.setObjectName("point_on_line_line")
        self.parallelism_widget = QtWidgets.QWidget(self.centralwidget)
        self.parallelism_widget.setGeometry(QtCore.QRect(50, 580, 241, 31))
        self.parallelism_widget.setMouseTracking(False)
        self.parallelism_widget.setAutoFillBackground(True)
        self.parallelism_widget.setObjectName("parallelism_widget")
        self.parallelism_submit = QtWidgets.QPushButton(self.parallelism_widget)
        self.parallelism_submit.setGeometry(QtCore.QRect(170, 0, 61, 25))
        self.parallelism_submit.setObjectName("parallelism_submit")
        self.parallelism_line_1 = QtWidgets.QCheckBox(self.parallelism_widget)
        self.parallelism_line_1.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.parallelism_line_1.setMouseTracking(False)
        self.parallelism_line_1.setShortcut("")
        self.parallelism_line_1.setCheckable(False)
        self.parallelism_line_1.setChecked(False)
        self.parallelism_line_1.setAutoRepeat(False)
        self.parallelism_line_1.setAutoExclusive(False)
        self.parallelism_line_1.setObjectName("parallelism_line_1")
        self.parallelism_line_2 = QtWidgets.QCheckBox(self.parallelism_widget)
        self.parallelism_line_2.setGeometry(QtCore.QRect(90, 0, 92, 23))
        self.parallelism_line_2.setCheckable(False)
        self.parallelism_line_2.setObjectName("parallelism_line_2")
        self.normal_widget = QtWidgets.QWidget(self.centralwidget)
        self.normal_widget.setGeometry(QtCore.QRect(50, 580, 241, 31))
        self.normal_widget.setAutoFillBackground(True)
        self.normal_widget.setObjectName("normal_widget")
        self.normal_submit = QtWidgets.QPushButton(self.normal_widget)
        self.normal_submit.setGeometry(QtCore.QRect(170, 0, 61, 25))
        self.normal_submit.setObjectName("normal_submit")
        self.normal_line_1 = QtWidgets.QCheckBox(self.normal_widget)
        self.normal_line_1.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.normal_line_1.setCheckable(False)
        self.normal_line_1.setObjectName("normal_line_1")
        self.normal_line_2 = QtWidgets.QCheckBox(self.normal_widget)
        self.normal_line_2.setGeometry(QtCore.QRect(90, 0, 92, 23))
        self.normal_line_2.setCheckable(False)
        self.normal_line_2.setObjectName("normal_line_2")
        self.horizontally_widget = QtWidgets.QWidget(self.centralwidget)
        self.horizontally_widget.setGeometry(QtCore.QRect(50, 580, 171, 31))
        self.horizontally_widget.setAutoFillBackground(True)
        self.horizontally_widget.setObjectName("horizontally_widget")
        self.horizontally_submit = QtWidgets.QPushButton(self.horizontally_widget)
        self.horizontally_submit.setGeometry(QtCore.QRect(90, 0, 61, 25))
        self.horizontally_submit.setObjectName("horizontally_submit")
        self.horizontally_line = QtWidgets.QCheckBox(self.horizontally_widget)
        self.horizontally_line.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.horizontally_line.setCheckable(False)
        self.horizontally_line.setObjectName("horizontally_line")
        self.fix_size_widget = QtWidgets.QWidget(self.centralwidget)
        self.fix_size_widget.setGeometry(QtCore.QRect(50, 580, 281, 31))
        self.fix_size_widget.setAutoFillBackground(True)
        self.fix_size_widget.setObjectName("fix_size_widget")
        self.label_37 = QtWidgets.QLabel(self.fix_size_widget)
        self.label_37.setGeometry(QtCore.QRect(70, -10, 51, 41))
        self.label_37.setObjectName("label_37")
        self.fix_size_submit = QtWidgets.QPushButton(self.fix_size_widget)
        self.fix_size_submit.setGeometry(QtCore.QRect(210, 0, 61, 25))
        self.fix_size_submit.setObjectName("fix_size_submit")
        self.fix_size_length = QtWidgets.QDoubleSpinBox(self.fix_size_widget)
        self.fix_size_length.setGeometry(QtCore.QRect(130, 0, 69, 26))
        self.fix_size_length.setObjectName("fix_size_length")
        self.fix_size_line = QtWidgets.QCheckBox(self.fix_size_widget)
        self.fix_size_line.setGeometry(QtCore.QRect(10, 0, 51, 23))
        self.fix_size_line.setCheckable(False)
        self.fix_size_line.setObjectName("fix_size_line")
        self.fix_point_widget = QtWidgets.QWidget(self.centralwidget)
        self.fix_point_widget.setGeometry(QtCore.QRect(50, 580, 171, 31))
        self.fix_point_widget.setAutoFillBackground(True)
        self.fix_point_widget.setObjectName("fix_point_widget")
        self.fix_point_submit = QtWidgets.QPushButton(self.fix_point_widget)
        self.fix_point_submit.setGeometry(QtCore.QRect(90, 0, 61, 25))
        self.fix_point_submit.setObjectName("fix_point_submit")
        self.fix_point_point = QtWidgets.QCheckBox(self.fix_point_widget)
        self.fix_point_point.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.fix_point_point.setCheckable(False)
        self.fix_point_point.setObjectName("fix_point_point")
        self.fix_length_widget = QtWidgets.QWidget(self.centralwidget)
        self.fix_length_widget.setGeometry(QtCore.QRect(50, 580, 171, 31))
        self.fix_length_widget.setAutoFillBackground(True)
        self.fix_length_widget.setObjectName("fix_length_widget")
        self.fix_length_submit = QtWidgets.QPushButton(self.fix_length_widget)
        self.fix_length_submit.setGeometry(QtCore.QRect(90, 0, 61, 25))
        self.fix_length_submit.setObjectName("fix_length_submit")
        self.fix_length_line = QtWidgets.QCheckBox(self.fix_length_widget)
        self.fix_length_line.setGeometry(QtCore.QRect(10, 0, 61, 23))
        self.fix_length_line.setCheckable(False)
        self.fix_length_line.setObjectName("fix_length_line")
        self.fix_angle_widget = QtWidgets.QWidget(self.centralwidget)
        self.fix_angle_widget.setGeometry(QtCore.QRect(50, 580, 241, 31))
        self.fix_angle_widget.setAutoFillBackground(True)
        self.fix_angle_widget.setObjectName("fix_angle_widget")
        self.fix_angle_submit = QtWidgets.QPushButton(self.fix_angle_widget)
        self.fix_angle_submit.setGeometry(QtCore.QRect(170, 0, 61, 25))
        self.fix_angle_submit.setObjectName("fix_angle_submit")
        self.fix_angle_line_1 = QtWidgets.QCheckBox(self.fix_angle_widget)
        self.fix_angle_line_1.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.fix_angle_line_1.setCheckable(False)
        self.fix_angle_line_1.setObjectName("fix_angle_line_1")
        self.fix_angle_line_2 = QtWidgets.QCheckBox(self.fix_angle_widget)
        self.fix_angle_line_2.setGeometry(QtCore.QRect(90, 0, 92, 23))
        self.fix_angle_line_2.setCheckable(False)
        self.fix_angle_line_2.setObjectName("fix_angle_line_2")
        self.footer_widget.raise_()
        self.work_plane.raise_()
        self.layoutWidget_2.raise_()
        self.listView.raise_()
        self.point_widget.raise_()
        self.line_widget.raise_()
        self.combine_points_widget.raise_()
        self.point_on_middle_line_widget.raise_()
        self.point_on_line_widget.raise_()
        self.parallelism_widget.raise_()
        self.normal_widget.raise_()
        self.horizontally_widget.raise_()
        self.fix_size_widget.raise_()
        self.fix_point_widget.raise_()
        self.fix_length_widget.raise_()
        self.fix_angle_widget.raise_()
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_menu = QtWidgets.QMenu(self.menubar)
        self.menu_menu.setObjectName("menu_menu")
        window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)
        self.action_new = QtWidgets.QAction(window)
        self.action_new.setObjectName("action_new")
        self.action_open = QtWidgets.QAction(window)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(window)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtWidgets.QAction(window)
        self.action_save_as.setObjectName("action_save_as")
        self.action_close = QtWidgets.QAction(window)
        self.action_close.setObjectName("action_close")
        self.action_undo = QtWidgets.QAction(window)
        self.action_undo.setObjectName("action_undo")
        self.action_redo = QtWidgets.QAction(window)
        self.action_redo.setObjectName("action_redo")
        self.action_show_elements_table = QtWidgets.QAction(window)
        self.action_show_elements_table.setCheckable(True)
        self.action_show_elements_table.setChecked(True)
        self.action_show_elements_table.setObjectName("action_show_elements_table")
        self.action_exit = QtWidgets.QAction(window)
        self.action_exit.setObjectName("action_exit")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_new)
        self.menuFile.addAction(self.action_open)
        self.menuFile.addAction(self.action_save)
        self.menuFile.addAction(self.action_save_as)
        self.menuFile.addAction(self.action_close)
        self.menuFile.addAction(self.action_exit)
        self.menu_menu.addSeparator()
        self.menu_menu.addAction(self.action_undo)
        self.menu_menu.addAction(self.action_redo)
        self.menu_menu.addAction(self.action_show_elements_table)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_menu.menuAction())

        self.retranslateUi(window)
        self.action_show_elements_table.triggered['bool'].connect(self.listView.hide)
        self.point.clicked['bool'].connect(self.point_widget.hide)
        self.line.clicked['bool'].connect(self.line_widget.hide)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "MainWindow"))
        self.label.setText(_translate("window", "X:"))
        self.label_2.setText(_translate("window", "Y:"))
        self.point_submit.setText(_translate("window", "Submit"))
        self.label_9.setText(_translate("window", "X1:"))
        self.label_10.setText(_translate("window", "Y1:"))
        self.line_submit.setText(_translate("window", "Submit"))
        self.label_11.setText(_translate("window", "X2:"))
        self.label_12.setText(_translate("window", "Y2:"))
        self.combine_points_submit.setText(_translate("window", "Submit"))
        self.combine_points_point_1.setText(_translate("window", "Point 1"))
        self.combine_points_point_2.setText(_translate("window", "Point 2"))
        self.point_on_middle_line_submit.setText(_translate("window", "Submit"))
        self.point_on_middle_line_point.setText(_translate("window", "Point"))
        self.point_on_middle_line_line.setText(_translate("window", "Line"))
        self.point_on_line_submit.setText(_translate("window", "Submit"))
        self.point_on_line_point.setText(_translate("window", "Point"))
        self.point_on_line_line.setText(_translate("window", "Line"))
        self.parallelism_submit.setText(_translate("window", "Submit"))
        self.parallelism_line_1.setText(_translate("window", "Line 1"))
        self.parallelism_line_2.setText(_translate("window", "Line 2"))
        self.normal_submit.setText(_translate("window", "Submit"))
        self.normal_line_1.setText(_translate("window", "Line 1"))
        self.normal_line_2.setText(_translate("window", "Line 2"))
        self.horizontally_submit.setText(_translate("window", "Submit"))
        self.horizontally_line.setText(_translate("window", "Line"))
        self.label_37.setText(_translate("window", "length:"))
        self.fix_size_submit.setText(_translate("window", "Submit"))
        self.fix_size_line.setText(_translate("window", "Line"))
        self.fix_point_submit.setText(_translate("window", "Submit"))
        self.fix_point_point.setText(_translate("window", "Point"))
        self.fix_length_submit.setText(_translate("window", "Submit"))
        self.fix_length_line.setText(_translate("window", "Line"))
        self.fix_angle_submit.setText(_translate("window", "Submit"))
        self.fix_angle_line_1.setText(_translate("window", "Line 1"))
        self.fix_angle_line_2.setText(_translate("window", "Line 2"))
        self.menuFile.setTitle(_translate("window", "File"))
        self.menu_menu.setTitle(_translate("window", "Menu"))
        self.action_new.setText(_translate("window", "New"))
        self.action_new.setShortcut(_translate("window", "Ctrl+N"))
        self.action_open.setText(_translate("window", "Open"))
        self.action_open.setShortcut(_translate("window", "Ctrl+O"))
        self.action_save.setText(_translate("window", "Save"))
        self.action_save.setShortcut(_translate("window", "Ctrl+S"))
        self.action_save_as.setText(_translate("window", "Save As"))
        self.action_save_as.setShortcut(_translate("window", "Ctrl+Shift+S"))
        self.action_close.setText(_translate("window", "Close"))
        self.action_close.setShortcut(_translate("window", "Ctrl+W"))
        self.action_undo.setText(_translate("window", "Undo"))
        self.action_undo.setShortcut(_translate("window", "Ctrl+Z"))
        self.action_redo.setText(_translate("window", "Redo"))
        self.action_redo.setShortcut(_translate("window", "Ctrl+Shift+Z"))
        self.action_show_elements_table.setText(_translate("window", "Show elements table"))
        self.action_show_elements_table.setShortcut(_translate("window", "Ctrl+T"))
        self.action_exit.setText(_translate("window", "Exit"))
        self.action_exit.setShortcut(_translate("window", "Ctrl+Q"))

