# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SuperCAD(object):
    def setupUi(self, SuperCAD):
        SuperCAD.setObjectName("SuperCAD")
        SuperCAD.resize(1280, 650)
        SuperCAD.setMinimumSize(QtCore.QSize(1280, 650))
        SuperCAD.setMaximumSize(QtCore.QSize(1280, 650))
        SuperCAD.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        SuperCAD.setMouseTracking(False)
        SuperCAD.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(SuperCAD)
        self.centralwidget.setObjectName("centralwidget")
        self.work_plane = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.work_plane.setGeometry(QtCore.QRect(50, 0, 1231, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.work_plane.sizePolicy().hasHeightForWidth())
        self.work_plane.setSizePolicy(sizePolicy)
        self.work_plane.setMouseTracking(True)
        self.work_plane.setAutoFillBackground(True)
        self.work_plane.setObjectName("work_plane")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 44, 471))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.Instruments = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.Instruments.setContentsMargins(0, 0, 0, 0)
        self.Instruments.setSpacing(0)
        self.Instruments.setObjectName("Instruments")
        self.point = QtWidgets.QPushButton(self.layoutWidget_2)
        self.point.setEnabled(True)
        self.point.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/point.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.point.setIcon(icon)
        self.point.setIconSize(QtCore.QSize(30, 30))
        self.point.setCheckable(True)
        self.point.setChecked(False)
        self.point.setAutoRepeat(True)
        self.point.setObjectName("point")
        self.Instruments.addWidget(self.point)
        self.line = QtWidgets.QPushButton(self.layoutWidget_2)
        self.line.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.line.setIcon(icon1)
        self.line.setIconSize(QtCore.QSize(30, 30))
        self.line.setCheckable(True)
        self.line.setAutoRepeat(True)
        self.line.setObjectName("line")
        self.Instruments.addWidget(self.line)
        self.combine_points = QtWidgets.QPushButton(self.layoutWidget_2)
        self.combine_points.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/combine_points.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combine_points.setIcon(icon2)
        self.combine_points.setIconSize(QtCore.QSize(30, 30))
        self.combine_points.setCheckable(True)
        self.combine_points.setAutoRepeat(True)
        self.combine_points.setObjectName("combine_points")
        self.Instruments.addWidget(self.combine_points)
        self.point_on_middle_line = QtWidgets.QPushButton(self.layoutWidget_2)
        self.point_on_middle_line.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/point_on_middle_line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.point_on_middle_line.setIcon(icon3)
        self.point_on_middle_line.setIconSize(QtCore.QSize(30, 30))
        self.point_on_middle_line.setCheckable(True)
        self.point_on_middle_line.setAutoRepeat(True)
        self.point_on_middle_line.setObjectName("point_on_middle_line")
        self.Instruments.addWidget(self.point_on_middle_line)
        self.point_on_line = QtWidgets.QPushButton(self.layoutWidget_2)
        self.point_on_line.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/point_on_line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.point_on_line.setIcon(icon4)
        self.point_on_line.setIconSize(QtCore.QSize(30, 30))
        self.point_on_line.setCheckable(True)
        self.point_on_line.setAutoRepeat(True)
        self.point_on_line.setObjectName("point_on_line")
        self.Instruments.addWidget(self.point_on_line)
        self.parallelism = QtWidgets.QPushButton(self.layoutWidget_2)
        self.parallelism.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/parallelism.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.parallelism.setIcon(icon5)
        self.parallelism.setIconSize(QtCore.QSize(30, 30))
        self.parallelism.setCheckable(True)
        self.parallelism.setAutoRepeat(True)
        self.parallelism.setObjectName("parallelism")
        self.Instruments.addWidget(self.parallelism)
        self.normal = QtWidgets.QPushButton(self.layoutWidget_2)
        self.normal.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/normal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.normal.setIcon(icon6)
        self.normal.setIconSize(QtCore.QSize(30, 30))
        self.normal.setCheckable(True)
        self.normal.setAutoRepeat(True)
        self.normal.setObjectName("normal")
        self.Instruments.addWidget(self.normal)
        self.horizontally = QtWidgets.QPushButton(self.layoutWidget_2)
        self.horizontally.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resources/horizontally.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.horizontally.setIcon(icon7)
        self.horizontally.setIconSize(QtCore.QSize(30, 30))
        self.horizontally.setCheckable(True)
        self.horizontally.setAutoRepeat(True)
        self.horizontally.setObjectName("horizontally")
        self.Instruments.addWidget(self.horizontally)
        self.fix_size = QtWidgets.QPushButton(self.layoutWidget_2)
        self.fix_size.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resources/fix_size.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fix_size.setIcon(icon8)
        self.fix_size.setIconSize(QtCore.QSize(30, 30))
        self.fix_size.setCheckable(True)
        self.fix_size.setAutoRepeat(True)
        self.fix_size.setObjectName("fix_size")
        self.Instruments.addWidget(self.fix_size)
        self.fix_point = QtWidgets.QPushButton(self.layoutWidget_2)
        self.fix_point.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resources/fix_point.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fix_point.setIcon(icon9)
        self.fix_point.setIconSize(QtCore.QSize(30, 30))
        self.fix_point.setCheckable(True)
        self.fix_point.setAutoRepeat(True)
        self.fix_point.setObjectName("fix_point")
        self.Instruments.addWidget(self.fix_point)
        self.fix_length = QtWidgets.QPushButton(self.layoutWidget_2)
        self.fix_length.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("resources/fix_length.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fix_length.setIcon(icon10)
        self.fix_length.setIconSize(QtCore.QSize(30, 30))
        self.fix_length.setCheckable(True)
        self.fix_length.setAutoRepeat(True)
        self.fix_length.setObjectName("fix_length")
        self.Instruments.addWidget(self.fix_length)
        self.fix_angle = QtWidgets.QPushButton(self.layoutWidget_2)
        self.fix_angle.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.fix_angle.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("resources/fix_angle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fix_angle.setIcon(icon11)
        self.fix_angle.setIconSize(QtCore.QSize(30, 30))
        self.fix_angle.setCheckable(True)
        self.fix_angle.setAutoRepeat(True)
        self.fix_angle.setObjectName("fix_angle")
        self.Instruments.addWidget(self.fix_angle)
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setEnabled(True)
        self.listView.setGeometry(QtCore.QRect(50, 0, 256, 581))
        self.listView.setAutoFillBackground(False)
        self.listView.setObjectName("listView")
        self.Point_widget = QtWidgets.QWidget(self.centralwidget)
        self.Point_widget.setGeometry(QtCore.QRect(50, 580, 281, 31))
        self.Point_widget.setAutoFillBackground(True)
        self.Point_widget.setObjectName("Point_widget")
        self.point_y = QtWidgets.QDoubleSpinBox(self.Point_widget)
        self.point_y.setGeometry(QtCore.QRect(130, 0, 69, 26))
        self.point_y.setObjectName("point_y")
        self.point_x = QtWidgets.QDoubleSpinBox(self.Point_widget)
        self.point_x.setGeometry(QtCore.QRect(30, 0, 69, 26))
        self.point_x.setObjectName("point_x")
        self.label = QtWidgets.QLabel(self.Point_widget)
        self.label.setGeometry(QtCore.QRect(10, -10, 20, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Point_widget)
        self.label_2.setGeometry(QtCore.QRect(110, -10, 20, 41))
        self.label_2.setObjectName("label_2")
        self.point_submit = QtWidgets.QPushButton(self.Point_widget)
        self.point_submit.setGeometry(QtCore.QRect(210, 0, 61, 25))
        self.point_submit.setObjectName("point_submit")
        self.footer_widget = QtWidgets.QWidget(self.centralwidget)
        self.footer_widget.setGeometry(QtCore.QRect(50, 580, 1231, 31))
        self.footer_widget.setAutoFillBackground(True)
        self.footer_widget.setObjectName("footer_widget")
        self.Line_widget = QtWidgets.QWidget(self.centralwidget)
        self.Line_widget.setGeometry(QtCore.QRect(50, 580, 521, 31))
        self.Line_widget.setAutoFillBackground(True)
        self.Line_widget.setObjectName("Line_widget")
        self.point_y1 = QtWidgets.QDoubleSpinBox(self.Line_widget)
        self.point_y1.setGeometry(QtCore.QRect(150, 0, 69, 26))
        self.point_y1.setObjectName("point_y1")
        self.point_x1 = QtWidgets.QDoubleSpinBox(self.Line_widget)
        self.point_x1.setGeometry(QtCore.QRect(40, 0, 69, 26))
        self.point_x1.setObjectName("point_x1")
        self.label_9 = QtWidgets.QLabel(self.Line_widget)
        self.label_9.setGeometry(QtCore.QRect(10, -10, 20, 41))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Line_widget)
        self.label_10.setGeometry(QtCore.QRect(120, -10, 20, 41))
        self.label_10.setObjectName("label_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.Line_widget)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 0, 61, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_11 = QtWidgets.QLabel(self.Line_widget)
        self.label_11.setGeometry(QtCore.QRect(230, -10, 20, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Line_widget)
        self.label_12.setGeometry(QtCore.QRect(340, -10, 20, 41))
        self.label_12.setObjectName("label_12")
        self.point_x2 = QtWidgets.QDoubleSpinBox(self.Line_widget)
        self.point_x2.setGeometry(QtCore.QRect(260, 0, 69, 26))
        self.point_x2.setObjectName("point_x2")
        self.point_y2 = QtWidgets.QDoubleSpinBox(self.Line_widget)
        self.point_y2.setGeometry(QtCore.QRect(370, 0, 69, 26))
        self.point_y2.setObjectName("point_y2")
        self.footer_widget.raise_()
        self.work_plane.raise_()
        self.layoutWidget_2.raise_()
        self.listView.raise_()
        self.Point_widget.raise_()
        self.Line_widget.raise_()
        SuperCAD.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SuperCAD)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        SuperCAD.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SuperCAD)
        self.statusbar.setObjectName("statusbar")
        SuperCAD.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(SuperCAD)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(SuperCAD)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(SuperCAD)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(SuperCAD)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionClose = QtWidgets.QAction(SuperCAD)
        self.actionClose.setObjectName("actionClose")
        self.actionUndo = QtWidgets.QAction(SuperCAD)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(SuperCAD)
        self.actionRedo.setObjectName("actionRedo")
        self.actionShow_elements_table = QtWidgets.QAction(SuperCAD)
        self.actionShow_elements_table.setCheckable(True)
        self.actionShow_elements_table.setChecked(True)
        self.actionShow_elements_table.setObjectName("actionShow_elements_table")
        self.actionExit = QtWidgets.QAction(SuperCAD)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionUndo)
        self.menuMenu.addAction(self.actionRedo)
        self.menuMenu.addAction(self.actionShow_elements_table)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(SuperCAD)
        self.actionShow_elements_table.triggered['bool'].connect(self.listView.hide)
        self.actionExit.changed.connect(SuperCAD.close)
        self.point.clicked['bool'].connect(self.Point_widget.hide)
        self.line.clicked['bool'].connect(self.Line_widget.hide)
        QtCore.QMetaObject.connectSlotsByName(SuperCAD)

    def retranslateUi(self, SuperCAD):
        _translate = QtCore.QCoreApplication.translate
        SuperCAD.setWindowTitle(_translate("SuperCAD", "MainWindow"))
        self.label.setText(_translate("SuperCAD", "X:"))
        self.label_2.setText(_translate("SuperCAD", "Y:"))
        self.point_submit.setText(_translate("SuperCAD", "Submit"))
        self.label_9.setText(_translate("SuperCAD", "X1:"))
        self.label_10.setText(_translate("SuperCAD", "Y1:"))
        self.pushButton_2.setText(_translate("SuperCAD", "Submit"))
        self.label_11.setText(_translate("SuperCAD", "X2:"))
        self.label_12.setText(_translate("SuperCAD", "Y2:"))
        self.menuFile.setTitle(_translate("SuperCAD", "File"))
        self.menuMenu.setTitle(_translate("SuperCAD", "Menu"))
        self.actionNew.setText(_translate("SuperCAD", "New"))
        self.actionNew.setShortcut(_translate("SuperCAD", "Ctrl+N"))
        self.actionOpen.setText(_translate("SuperCAD", "Open"))
        self.actionOpen.setShortcut(_translate("SuperCAD", "Ctrl+O"))
        self.actionSave.setText(_translate("SuperCAD", "Save"))
        self.actionSave.setShortcut(_translate("SuperCAD", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("SuperCAD", "Save As"))
        self.actionSaveAs.setShortcut(_translate("SuperCAD", "Ctrl+Shift+S"))
        self.actionClose.setText(_translate("SuperCAD", "Close"))
        self.actionClose.setShortcut(_translate("SuperCAD", "Ctrl+W"))
        self.actionUndo.setText(_translate("SuperCAD", "Undo"))
        self.actionUndo.setShortcut(_translate("SuperCAD", "Ctrl+Z"))
        self.actionRedo.setText(_translate("SuperCAD", "Redo"))
        self.actionRedo.setShortcut(_translate("SuperCAD", "Ctrl+Shift+Z"))
        self.actionShow_elements_table.setText(_translate("SuperCAD", "Show elements table"))
        self.actionShow_elements_table.setShortcut(_translate("SuperCAD", "Ctrl+T"))
        self.actionExit.setText(_translate("SuperCAD", "Exit"))
        self.actionExit.setShortcut(_translate("SuperCAD", "Ctrl+Q"))

