"""Module for setup design generated by Qtdesignee and functionality module"""
import design
# import design_functionality


class UiAddDesign(design.Ui_SuperCAD):
    def setup_ui(self, window):
        super().setupUi(window)

        self.listView.hide()
        self.hide_all_footer_widgets()
        self.actionShow_elements_table.triggered['bool'].connect(
            self.triggered_list_view)
        self.point.clicked['bool'].connect(
            self.triggered_widget("Point_widget"))
        self.line.clicked['bool'].connect(
            self.triggered_widget("Line_widget"))
        self.combine_points.clicked['bool'].connect(
            self.triggered_widget("Combine_points_widget"))
        self.point_on_middle_line.clicked['bool'].connect(
            self.triggered_widget("Point_on_middle_line_widget"))
        self.point_on_line.clicked['bool'].connect(
            self.triggered_widget("Point_on_line_widget"))
        self.parallelism.clicked['bool'].connect(
            self.triggered_widget("Parallelism_widget"))
        self.normal.clicked['bool'].connect(
            self.triggered_widget("Normal_widget"))
        self.horizontally.clicked['bool'].connect(
            self.triggered_widget("Horizontally_widget"))
        self.fix_size.clicked['bool'].connect(
            self.triggered_widget("Fix_size_widget"))
        self.fix_point.clicked['bool'].connect(
            self.triggered_widget("Fix_point_widget"))
        self.fix_length.clicked['bool'].connect(
            self.triggered_widget("Fix_length_widget"))
        self.fix_angle.clicked['bool'].connect(
            self.triggered_widget("Fix_angle_widget"))
