# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(1280, 650)
        window.setMinimumSize(QtCore.QSize(1280, 650))
        window.setMaximumSize(QtCore.QSize(1280, 650))
        window.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        window.setMouseTracking(False)
        window.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.work_plane = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.work_plane.setGeometry(QtCore.QRect(50, 0, 1231, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.work_plane.sizePolicy().hasHeightForWidth())
        self.work_plane.setSizePolicy(sizePolicy)
        self.work_plane.setMouseTracking(True)
        self.work_plane.setAutoFillBackground(True)
        self.work_plane.setObjectName("work_plane")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 50, 471))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.Instruments = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.Instruments.setContentsMargins(0, 0, 0, 0)
        self.Instruments.setSpacing(0)
        self.Instruments.setObjectName("Instruments")
        self.button_add_point = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_add_point.setEnabled(True)
        self.button_add_point.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/point.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_add_point.setIcon(icon)
        self.button_add_point.setIconSize(QtCore.QSize(30, 30))
        self.button_add_point.setCheckable(True)
        self.button_add_point.setChecked(False)
        self.button_add_point.setAutoRepeat(True)
        self.button_add_point.setObjectName("button_add_point")
        self.Instruments.addWidget(self.button_add_point)
        self.button_add_segment = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_add_segment.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_add_segment.setIcon(icon1)
        self.button_add_segment.setIconSize(QtCore.QSize(30, 30))
        self.button_add_segment.setCheckable(True)
        self.button_add_segment.setAutoRepeat(True)
        self.button_add_segment.setObjectName("button_add_segment")
        self.Instruments.addWidget(self.button_add_segment)
        self.button_restr_joint = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_restr_joint.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/combine_points.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_restr_joint.setIcon(icon2)
        self.button_restr_joint.setIconSize(QtCore.QSize(30, 30))
        self.button_restr_joint.setCheckable(True)
        self.button_restr_joint.setAutoRepeat(True)
        self.button_restr_joint.setObjectName("button_restr_joint")
        self.Instruments.addWidget(self.button_restr_joint)
        self.button_restr_point_on_segment = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_restr_point_on_segment.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/point_on_line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_restr_point_on_segment.setIcon(icon3)
        self.button_restr_point_on_segment.setIconSize(QtCore.QSize(30, 30))
        self.button_restr_point_on_segment.setCheckable(True)
        self.button_restr_point_on_segment.setAutoRepeat(True)
        self.button_restr_point_on_segment.setObjectName("button_restr_point_on_segment")
        self.Instruments.addWidget(self.button_restr_point_on_segment)
        self.button_restr_segments_parallel = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_restr_segments_parallel.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/point_on_middle_line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_restr_segments_parallel.setIcon(icon4)
        self.button_restr_segments_parallel.setIconSize(QtCore.QSize(30, 30))
        self.button_restr_segments_parallel.setCheckable(True)
        self.button_restr_segments_parallel.setAutoRepeat(True)
        self.button_restr_segments_parallel.setObjectName("button_restr_segments_parallel")
        self.Instruments.addWidget(self.button_restr_segments_parallel)
        self.button_restr_segments_normal = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_restr_segments_normal.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/normal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_restr_segments_normal.setIcon(icon5)
        self.button_restr_segments_normal.setIconSize(QtCore.QSize(30, 30))
        self.button_restr_segments_normal.setCheckable(True)
        self.button_restr_segments_normal.setAutoRepeat(True)
        self.button_restr_segments_normal.setObjectName("button_restr_segments_normal")
        self.Instruments.addWidget(self.button_restr_segments_normal)
        self.button_restr_segment_horizontal = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_restr_segment_horizontal.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/horizontally.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_restr_segment_horizontal.setIcon(icon6)
        self.button_restr_segment_horizontal.setIconSize(QtCore.QSize(30, 30))
        self.button_restr_segment_horizontal.setCheckable(True)
        self.button_restr_segment_horizontal.setAutoRepeat(True)
        self.button_restr_segment_horizontal.setObjectName("button_restr_segment_horizontal")
        self.Instruments.addWidget(self.button_restr_segment_horizontal)
        self.button_restr_fixed = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_restr_fixed.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resources/fix_point.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_restr_fixed.setIcon(icon7)
        self.button_restr_fixed.setIconSize(QtCore.QSize(30, 30))
        self.button_restr_fixed.setCheckable(True)
        self.button_restr_fixed.setAutoRepeat(True)
        self.button_restr_fixed.setObjectName("button_restr_fixed")
        self.Instruments.addWidget(self.button_restr_fixed)
        self.button_restr_segment_length_fixed = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_restr_segment_length_fixed.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resources/fix_length.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_restr_segment_length_fixed.setIcon(icon8)
        self.button_restr_segment_length_fixed.setIconSize(QtCore.QSize(30, 30))
        self.button_restr_segment_length_fixed.setCheckable(True)
        self.button_restr_segment_length_fixed.setAutoRepeat(True)
        self.button_restr_segment_length_fixed.setObjectName("button_restr_segment_length_fixed")
        self.Instruments.addWidget(self.button_restr_segment_length_fixed)
        self.button_restr_segment_angle_fixed = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_restr_segment_angle_fixed.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_restr_segment_angle_fixed.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resources/fix_angle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_restr_segment_angle_fixed.setIcon(icon9)
        self.button_restr_segment_angle_fixed.setIconSize(QtCore.QSize(30, 30))
        self.button_restr_segment_angle_fixed.setCheckable(True)
        self.button_restr_segment_angle_fixed.setAutoRepeat(True)
        self.button_restr_segment_angle_fixed.setObjectName("button_restr_segment_angle_fixed")
        self.Instruments.addWidget(self.button_restr_segment_angle_fixed)
        self.widget_elements_table = QtWidgets.QListView(self.centralwidget)
        self.widget_elements_table.setEnabled(True)
        self.widget_elements_table.setGeometry(QtCore.QRect(50, 0, 256, 581))
        self.widget_elements_table.setAutoFillBackground(False)
        self.widget_elements_table.setObjectName("widget_elements_table")
        self.widget_add_point = QtWidgets.QWidget(self.centralwidget)
        self.widget_add_point.setGeometry(QtCore.QRect(50, 580, 281, 31))
        self.widget_add_point.setFocusPolicy(QtCore.Qt.TabFocus)
        self.widget_add_point.setAutoFillBackground(True)
        self.widget_add_point.setObjectName("widget_add_point")
        self.field_y_add_point = QtWidgets.QDoubleSpinBox(self.widget_add_point)
        self.field_y_add_point.setGeometry(QtCore.QRect(130, 0, 69, 26))
        self.field_y_add_point.setKeyboardTracking(False)
        self.field_y_add_point.setMinimum(-9e+17)
        self.field_y_add_point.setMaximum(9e+17)
        self.field_y_add_point.setSingleStep(1.0)
        self.field_y_add_point.setProperty("value", 0.0)
        self.field_y_add_point.setObjectName("field_y_add_point")
        self.field_x_add_point = QtWidgets.QDoubleSpinBox(self.widget_add_point)
        self.field_x_add_point.setGeometry(QtCore.QRect(30, 0, 69, 26))
        self.field_x_add_point.setKeyboardTracking(False)
        self.field_x_add_point.setMinimum(-9e+17)
        self.field_x_add_point.setMaximum(9e+17)
        self.field_x_add_point.setSingleStep(1.0)
        self.field_x_add_point.setProperty("value", 0.0)
        self.field_x_add_point.setObjectName("field_x_add_point")
        self.label_x_add_point = QtWidgets.QLabel(self.widget_add_point)
        self.label_x_add_point.setGeometry(QtCore.QRect(10, -10, 20, 41))
        self.label_x_add_point.setObjectName("label_x_add_point")
        self.label_y_add_point = QtWidgets.QLabel(self.widget_add_point)
        self.label_y_add_point.setGeometry(QtCore.QRect(110, -10, 20, 41))
        self.label_y_add_point.setObjectName("label_y_add_point")
        self.submit_add_point = QtWidgets.QPushButton(self.widget_add_point)
        self.submit_add_point.setGeometry(QtCore.QRect(210, 0, 61, 25))
        self.submit_add_point.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit_add_point.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.submit_add_point.setAutoDefault(True)
        self.submit_add_point.setObjectName("submit_add_point")
        self.footer_widget = QtWidgets.QWidget(self.centralwidget)
        self.footer_widget.setGeometry(QtCore.QRect(50, 580, 1231, 31))
        self.footer_widget.setAutoFillBackground(True)
        self.footer_widget.setObjectName("footer_widget")
        self.widget_add_segment = QtWidgets.QWidget(self.centralwidget)
        self.widget_add_segment.setGeometry(QtCore.QRect(50, 580, 521, 31))
        self.widget_add_segment.setAutoFillBackground(True)
        self.widget_add_segment.setObjectName("widget_add_segment")
        self.field_y1_add_segment = QtWidgets.QDoubleSpinBox(self.widget_add_segment)
        self.field_y1_add_segment.setGeometry(QtCore.QRect(150, 0, 69, 26))
        self.field_y1_add_segment.setKeyboardTracking(False)
        self.field_y1_add_segment.setMinimum(-9e+17)
        self.field_y1_add_segment.setMaximum(9e+17)
        self.field_y1_add_segment.setSingleStep(1.0)
        self.field_y1_add_segment.setProperty("value", 0.0)
        self.field_y1_add_segment.setObjectName("field_y1_add_segment")
        self.field_x1_add_segment = QtWidgets.QDoubleSpinBox(self.widget_add_segment)
        self.field_x1_add_segment.setGeometry(QtCore.QRect(40, 0, 69, 26))
        self.field_x1_add_segment.setKeyboardTracking(False)
        self.field_x1_add_segment.setMinimum(-9e+17)
        self.field_x1_add_segment.setMaximum(9e+17)
        self.field_x1_add_segment.setSingleStep(1.0)
        self.field_x1_add_segment.setProperty("value", 0.0)
        self.field_x1_add_segment.setObjectName("field_x1_add_segment")
        self.label_x1_add_segment = QtWidgets.QLabel(self.widget_add_segment)
        self.label_x1_add_segment.setGeometry(QtCore.QRect(10, -10, 20, 41))
        self.label_x1_add_segment.setObjectName("label_x1_add_segment")
        self.label_y1_add_segment = QtWidgets.QLabel(self.widget_add_segment)
        self.label_y1_add_segment.setGeometry(QtCore.QRect(120, -10, 20, 41))
        self.label_y1_add_segment.setObjectName("label_y1_add_segment")
        self.submit_add_segment = QtWidgets.QPushButton(self.widget_add_segment)
        self.submit_add_segment.setGeometry(QtCore.QRect(460, 0, 61, 25))
        self.submit_add_segment.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit_add_segment.setAutoDefault(True)
        self.submit_add_segment.setObjectName("submit_add_segment")
        self.label_x2_add_segment = QtWidgets.QLabel(self.widget_add_segment)
        self.label_x2_add_segment.setGeometry(QtCore.QRect(230, -10, 20, 41))
        self.label_x2_add_segment.setObjectName("label_x2_add_segment")
        self.label_y2_add_segment = QtWidgets.QLabel(self.widget_add_segment)
        self.label_y2_add_segment.setGeometry(QtCore.QRect(340, -10, 20, 41))
        self.label_y2_add_segment.setObjectName("label_y2_add_segment")
        self.field_x2_add_segment = QtWidgets.QDoubleSpinBox(self.widget_add_segment)
        self.field_x2_add_segment.setGeometry(QtCore.QRect(260, 0, 69, 26))
        self.field_x2_add_segment.setKeyboardTracking(False)
        self.field_x2_add_segment.setMinimum(-9e+17)
        self.field_x2_add_segment.setMaximum(9e+17)
        self.field_x2_add_segment.setSingleStep(1.0)
        self.field_x2_add_segment.setProperty("value", 0.0)
        self.field_x2_add_segment.setObjectName("field_x2_add_segment")
        self.field_y2_add_segment = QtWidgets.QDoubleSpinBox(self.widget_add_segment)
        self.field_y2_add_segment.setGeometry(QtCore.QRect(370, 0, 69, 26))
        self.field_y2_add_segment.setKeyboardTracking(False)
        self.field_y2_add_segment.setMinimum(-9e+17)
        self.field_y2_add_segment.setMaximum(9e+17)
        self.field_y2_add_segment.setSingleStep(1.0)
        self.field_y2_add_segment.setProperty("value", 0.0)
        self.field_y2_add_segment.setObjectName("field_y2_add_segment")
        self.widget_restr_joint = QtWidgets.QWidget(self.centralwidget)
        self.widget_restr_joint.setGeometry(QtCore.QRect(50, 580, 281, 31))
        self.widget_restr_joint.setAutoFillBackground(True)
        self.widget_restr_joint.setObjectName("widget_restr_joint")
        self.submit_restr_joint = QtWidgets.QPushButton(self.widget_restr_joint)
        self.submit_restr_joint.setGeometry(QtCore.QRect(210, 0, 61, 25))
        self.submit_restr_joint.setObjectName("submit_restr_joint")
        self.checkbox_restr_joint_1 = QtWidgets.QCheckBox(self.widget_restr_joint)
        self.checkbox_restr_joint_1.setGeometry(QtCore.QRect(10, 0, 101, 23))
        self.checkbox_restr_joint_1.setCheckable(True)
        self.checkbox_restr_joint_1.setChecked(False)
        self.checkbox_restr_joint_1.setObjectName("checkbox_restr_joint_1")
        self.checkbox_restr_joint_2 = QtWidgets.QCheckBox(self.widget_restr_joint)
        self.checkbox_restr_joint_2.setGeometry(QtCore.QRect(115, 0, 92, 23))
        self.checkbox_restr_joint_2.setCheckable(True)
        self.checkbox_restr_joint_2.setChecked(False)
        self.checkbox_restr_joint_2.setObjectName("checkbox_restr_joint_2")
        self.widget_restr_point_on_segment = QtWidgets.QWidget(self.centralwidget)
        self.widget_restr_point_on_segment.setGeometry(QtCore.QRect(50, 580, 241, 31))
        self.widget_restr_point_on_segment.setAutoFillBackground(True)
        self.widget_restr_point_on_segment.setObjectName("widget_restr_point_on_segment")
        self.submit_restr_point_on_segment = QtWidgets.QPushButton(self.widget_restr_point_on_segment)
        self.submit_restr_point_on_segment.setGeometry(QtCore.QRect(170, 0, 61, 25))
        self.submit_restr_point_on_segment.setObjectName("submit_restr_point_on_segment")
        self.checkbox_restr_point_on_segment_point = QtWidgets.QCheckBox(self.widget_restr_point_on_segment)
        self.checkbox_restr_point_on_segment_point.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.checkbox_restr_point_on_segment_point.setCheckable(True)
        self.checkbox_restr_point_on_segment_point.setChecked(False)
        self.checkbox_restr_point_on_segment_point.setObjectName("checkbox_restr_point_on_segment_point")
        self.checkbox_restr_point_on_segment_line = QtWidgets.QCheckBox(self.widget_restr_point_on_segment)
        self.checkbox_restr_point_on_segment_line.setGeometry(QtCore.QRect(90, 0, 92, 23))
        self.checkbox_restr_point_on_segment_line.setCheckable(True)
        self.checkbox_restr_point_on_segment_line.setChecked(False)
        self.checkbox_restr_point_on_segment_line.setObjectName("checkbox_restr_point_on_segment_line")
        self.widget_restr_segments_parallel = QtWidgets.QWidget(self.centralwidget)
        self.widget_restr_segments_parallel.setGeometry(QtCore.QRect(50, 580, 241, 31))
        self.widget_restr_segments_parallel.setMouseTracking(False)
        self.widget_restr_segments_parallel.setAutoFillBackground(True)
        self.widget_restr_segments_parallel.setObjectName("widget_restr_segments_parallel")
        self.submit_restr_segments_parallel = QtWidgets.QPushButton(self.widget_restr_segments_parallel)
        self.submit_restr_segments_parallel.setGeometry(QtCore.QRect(170, 0, 61, 25))
        self.submit_restr_segments_parallel.setObjectName("submit_restr_segments_parallel")
        self.checkbox_restr_segments_parallel_1 = QtWidgets.QCheckBox(self.widget_restr_segments_parallel)
        self.checkbox_restr_segments_parallel_1.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.checkbox_restr_segments_parallel_1.setMouseTracking(False)
        self.checkbox_restr_segments_parallel_1.setShortcut("")
        self.checkbox_restr_segments_parallel_1.setCheckable(True)
        self.checkbox_restr_segments_parallel_1.setChecked(False)
        self.checkbox_restr_segments_parallel_1.setAutoRepeat(False)
        self.checkbox_restr_segments_parallel_1.setAutoExclusive(False)
        self.checkbox_restr_segments_parallel_1.setObjectName("checkbox_restr_segments_parallel_1")
        self.checkbox_restr_segments_parallel_2 = QtWidgets.QCheckBox(self.widget_restr_segments_parallel)
        self.checkbox_restr_segments_parallel_2.setGeometry(QtCore.QRect(90, 0, 92, 23))
        self.checkbox_restr_segments_parallel_2.setCheckable(True)
        self.checkbox_restr_segments_parallel_2.setChecked(False)
        self.checkbox_restr_segments_parallel_2.setObjectName("checkbox_restr_segments_parallel_2")
        self.widget_restr_segments_normal = QtWidgets.QWidget(self.centralwidget)
        self.widget_restr_segments_normal.setGeometry(QtCore.QRect(50, 580, 241, 31))
        self.widget_restr_segments_normal.setAutoFillBackground(True)
        self.widget_restr_segments_normal.setObjectName("widget_restr_segments_normal")
        self.submit_restr_segments_normal = QtWidgets.QPushButton(self.widget_restr_segments_normal)
        self.submit_restr_segments_normal.setGeometry(QtCore.QRect(170, 0, 61, 25))
        self.submit_restr_segments_normal.setObjectName("submit_restr_segments_normal")
        self.checkbox_restr_segments_normal_1 = QtWidgets.QCheckBox(self.widget_restr_segments_normal)
        self.checkbox_restr_segments_normal_1.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.checkbox_restr_segments_normal_1.setCheckable(True)
        self.checkbox_restr_segments_normal_1.setChecked(False)
        self.checkbox_restr_segments_normal_1.setObjectName("checkbox_restr_segments_normal_1")
        self.checkbox_restr_segments_normal_2 = QtWidgets.QCheckBox(self.widget_restr_segments_normal)
        self.checkbox_restr_segments_normal_2.setGeometry(QtCore.QRect(90, 0, 92, 23))
        self.checkbox_restr_segments_normal_2.setCheckable(True)
        self.checkbox_restr_segments_normal_2.setChecked(False)
        self.checkbox_restr_segments_normal_2.setObjectName("checkbox_restr_segments_normal_2")
        self.widget_restr_segment_horizontal = QtWidgets.QWidget(self.centralwidget)
        self.widget_restr_segment_horizontal.setGeometry(QtCore.QRect(50, 580, 171, 31))
        self.widget_restr_segment_horizontal.setAutoFillBackground(True)
        self.widget_restr_segment_horizontal.setObjectName("widget_restr_segment_horizontal")
        self.submit_restr_segment_horizontal = QtWidgets.QPushButton(self.widget_restr_segment_horizontal)
        self.submit_restr_segment_horizontal.setGeometry(QtCore.QRect(90, 0, 61, 25))
        self.submit_restr_segment_horizontal.setObjectName("submit_restr_segment_horizontal")
        self.checkbox_restr_segment_horizontal = QtWidgets.QCheckBox(self.widget_restr_segment_horizontal)
        self.checkbox_restr_segment_horizontal.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.checkbox_restr_segment_horizontal.setCheckable(True)
        self.checkbox_restr_segment_horizontal.setChecked(False)
        self.checkbox_restr_segment_horizontal.setObjectName("checkbox_restr_segment_horizontal")
        self.widget_restr_fixed = QtWidgets.QWidget(self.centralwidget)
        self.widget_restr_fixed.setGeometry(QtCore.QRect(50, 580, 171, 31))
        self.widget_restr_fixed.setAutoFillBackground(True)
        self.widget_restr_fixed.setObjectName("widget_restr_fixed")
        self.submit_restr_fixed = QtWidgets.QPushButton(self.widget_restr_fixed)
        self.submit_restr_fixed.setGeometry(QtCore.QRect(90, 0, 61, 25))
        self.submit_restr_fixed.setObjectName("submit_restr_fixed")
        self.checkbox_restr_fixed = QtWidgets.QCheckBox(self.widget_restr_fixed)
        self.checkbox_restr_fixed.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.checkbox_restr_fixed.setCheckable(True)
        self.checkbox_restr_fixed.setChecked(False)
        self.checkbox_restr_fixed.setObjectName("checkbox_restr_fixed")
        self.widget_restr_segment_length_fixed = QtWidgets.QWidget(self.centralwidget)
        self.widget_restr_segment_length_fixed.setGeometry(QtCore.QRect(50, 580, 171, 31))
        self.widget_restr_segment_length_fixed.setAutoFillBackground(True)
        self.widget_restr_segment_length_fixed.setObjectName("widget_restr_segment_length_fixed")
        self.submit_restr_segment_length_fixed = QtWidgets.QPushButton(self.widget_restr_segment_length_fixed)
        self.submit_restr_segment_length_fixed.setGeometry(QtCore.QRect(90, 0, 61, 25))
        self.submit_restr_segment_length_fixed.setObjectName("submit_restr_segment_length_fixed")
        self.checkbox_restr_segment_length_fixed = QtWidgets.QCheckBox(self.widget_restr_segment_length_fixed)
        self.checkbox_restr_segment_length_fixed.setGeometry(QtCore.QRect(10, 0, 61, 23))
        self.checkbox_restr_segment_length_fixed.setCheckable(True)
        self.checkbox_restr_segment_length_fixed.setChecked(False)
        self.checkbox_restr_segment_length_fixed.setObjectName("checkbox_restr_segment_length_fixed")
        self.widget_restr_segment_angle_fixed = QtWidgets.QWidget(self.centralwidget)
        self.widget_restr_segment_angle_fixed.setGeometry(QtCore.QRect(50, 580, 241, 31))
        self.widget_restr_segment_angle_fixed.setAutoFillBackground(True)
        self.widget_restr_segment_angle_fixed.setObjectName("widget_restr_segment_angle_fixed")
        self.submit_restr_segment_angle_fixed = QtWidgets.QPushButton(self.widget_restr_segment_angle_fixed)
        self.submit_restr_segment_angle_fixed.setGeometry(QtCore.QRect(170, 0, 61, 25))
        self.submit_restr_segment_angle_fixed.setObjectName("submit_restr_segment_angle_fixed")
        self.checkbox_restr_segment_angle_fixed_1 = QtWidgets.QCheckBox(self.widget_restr_segment_angle_fixed)
        self.checkbox_restr_segment_angle_fixed_1.setGeometry(QtCore.QRect(10, 0, 92, 23))
        self.checkbox_restr_segment_angle_fixed_1.setCheckable(True)
        self.checkbox_restr_segment_angle_fixed_1.setChecked(False)
        self.checkbox_restr_segment_angle_fixed_1.setAutoRepeat(False)
        self.checkbox_restr_segment_angle_fixed_1.setTristate(False)
        self.checkbox_restr_segment_angle_fixed_1.setObjectName("checkbox_restr_segment_angle_fixed_1")
        self.checkbox_restr_segment_angle_fixed_2 = QtWidgets.QCheckBox(self.widget_restr_segment_angle_fixed)
        self.checkbox_restr_segment_angle_fixed_2.setGeometry(QtCore.QRect(90, 0, 92, 23))
        self.checkbox_restr_segment_angle_fixed_2.setCheckable(True)
        self.checkbox_restr_segment_angle_fixed_2.setChecked(False)
        self.checkbox_restr_segment_angle_fixed_2.setObjectName("checkbox_restr_segment_angle_fixed_2")
        self.footer_widget.raise_()
        self.work_plane.raise_()
        self.layoutWidget_2.raise_()
        self.widget_elements_table.raise_()
        self.widget_restr_point_on_segment.raise_()
        self.widget_restr_segments_normal.raise_()
        self.widget_restr_segment_horizontal.raise_()
        self.widget_restr_segment_length_fixed.raise_()
        self.widget_restr_segment_angle_fixed.raise_()
        self.widget_restr_segments_parallel.raise_()
        self.widget_restr_fixed.raise_()
        self.widget_restr_joint.raise_()
        self.widget_add_point.raise_()
        self.widget_add_segment.raise_()
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_menu = QtWidgets.QMenu(self.menubar)
        self.menu_menu.setObjectName("menu_menu")
        window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)
        self.action_new = QtWidgets.QAction(window)
        self.action_new.setObjectName("action_new")
        self.action_open = QtWidgets.QAction(window)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(window)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtWidgets.QAction(window)
        self.action_save_as.setObjectName("action_save_as")
        self.action_close = QtWidgets.QAction(window)
        self.action_close.setObjectName("action_close")
        self.action_undo = QtWidgets.QAction(window)
        self.action_undo.setObjectName("action_undo")
        self.action_redo = QtWidgets.QAction(window)
        self.action_redo.setObjectName("action_redo")
        self.action_show_elements_table = QtWidgets.QAction(window)
        self.action_show_elements_table.setCheckable(True)
        self.action_show_elements_table.setChecked(True)
        self.action_show_elements_table.setObjectName("action_show_elements_table")
        self.action_exit = QtWidgets.QAction(window)
        self.action_exit.setObjectName("action_exit")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_new)
        self.menuFile.addAction(self.action_open)
        self.menuFile.addAction(self.action_save)
        self.menuFile.addAction(self.action_save_as)
        self.menuFile.addAction(self.action_close)
        self.menuFile.addAction(self.action_exit)
        self.menu_menu.addSeparator()
        self.menu_menu.addAction(self.action_undo)
        self.menu_menu.addAction(self.action_redo)
        self.menu_menu.addAction(self.action_show_elements_table)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_menu.menuAction())

        self.retranslateUi(window)
        self.action_show_elements_table.triggered['bool'].connect(self.widget_elements_table.hide)
        self.button_add_point.clicked['bool'].connect(self.widget_add_point.hide)
        self.button_add_segment.clicked['bool'].connect(self.widget_add_segment.hide)
        QtCore.QMetaObject.connectSlotsByName(window)
        window.setTabOrder(self.button_add_point, self.button_add_segment)
        window.setTabOrder(self.button_add_segment, self.button_restr_joint)
        window.setTabOrder(self.button_restr_joint, self.button_restr_point_on_segment)
        window.setTabOrder(self.button_restr_point_on_segment, self.button_restr_segments_parallel)
        window.setTabOrder(self.button_restr_segments_parallel, self.button_restr_segments_normal)
        window.setTabOrder(self.button_restr_segments_normal, self.button_restr_segment_horizontal)
        window.setTabOrder(self.button_restr_segment_horizontal, self.button_restr_fixed)
        window.setTabOrder(self.button_restr_fixed, self.button_restr_segment_length_fixed)
        window.setTabOrder(self.button_restr_segment_length_fixed, self.button_restr_segment_angle_fixed)
        window.setTabOrder(self.button_restr_segment_angle_fixed, self.widget_elements_table)
        window.setTabOrder(self.widget_elements_table, self.widget_add_point)
        window.setTabOrder(self.widget_add_point, self.field_y_add_point)
        window.setTabOrder(self.field_y_add_point, self.field_x_add_point)
        window.setTabOrder(self.field_x_add_point, self.submit_add_point)
        window.setTabOrder(self.submit_add_point, self.field_y1_add_segment)
        window.setTabOrder(self.field_y1_add_segment, self.field_x1_add_segment)
        window.setTabOrder(self.field_x1_add_segment, self.submit_add_segment)
        window.setTabOrder(self.submit_add_segment, self.field_x2_add_segment)
        window.setTabOrder(self.field_x2_add_segment, self.field_y2_add_segment)
        window.setTabOrder(self.field_y2_add_segment, self.submit_restr_joint)
        window.setTabOrder(self.submit_restr_joint, self.checkbox_restr_joint_1)
        window.setTabOrder(self.checkbox_restr_joint_1, self.checkbox_restr_joint_2)
        window.setTabOrder(self.checkbox_restr_joint_2, self.submit_restr_point_on_segment)
        window.setTabOrder(self.submit_restr_point_on_segment, self.checkbox_restr_point_on_segment_point)
        window.setTabOrder(self.checkbox_restr_point_on_segment_point, self.checkbox_restr_point_on_segment_line)
        window.setTabOrder(self.checkbox_restr_point_on_segment_line, self.submit_restr_segments_parallel)
        window.setTabOrder(self.submit_restr_segments_parallel, self.checkbox_restr_segments_parallel_1)
        window.setTabOrder(self.checkbox_restr_segments_parallel_1, self.checkbox_restr_segments_parallel_2)
        window.setTabOrder(self.checkbox_restr_segments_parallel_2, self.submit_restr_segments_normal)
        window.setTabOrder(self.submit_restr_segments_normal, self.checkbox_restr_segments_normal_1)
        window.setTabOrder(self.checkbox_restr_segments_normal_1, self.checkbox_restr_segments_normal_2)
        window.setTabOrder(self.checkbox_restr_segments_normal_2, self.submit_restr_segment_horizontal)
        window.setTabOrder(self.submit_restr_segment_horizontal, self.checkbox_restr_segment_horizontal)
        window.setTabOrder(self.checkbox_restr_segment_horizontal, self.submit_restr_fixed)
        window.setTabOrder(self.submit_restr_fixed, self.checkbox_restr_fixed)
        window.setTabOrder(self.checkbox_restr_fixed, self.submit_restr_segment_length_fixed)
        window.setTabOrder(self.submit_restr_segment_length_fixed, self.checkbox_restr_segment_length_fixed)
        window.setTabOrder(self.checkbox_restr_segment_length_fixed, self.submit_restr_segment_angle_fixed)
        window.setTabOrder(self.submit_restr_segment_angle_fixed, self.checkbox_restr_segment_angle_fixed_1)
        window.setTabOrder(self.checkbox_restr_segment_angle_fixed_1, self.checkbox_restr_segment_angle_fixed_2)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "MainWindow"))
        self.label_x_add_point.setText(_translate("window", "X:"))
        self.label_y_add_point.setText(_translate("window", "Y:"))
        self.submit_add_point.setText(_translate("window", "Submit"))
        self.label_x1_add_segment.setText(_translate("window", "X1:"))
        self.label_y1_add_segment.setText(_translate("window", "Y1:"))
        self.submit_add_segment.setText(_translate("window", "Submit"))
        self.label_x2_add_segment.setText(_translate("window", "X2:"))
        self.label_y2_add_segment.setText(_translate("window", "Y2:"))
        self.submit_restr_joint.setText(_translate("window", "Submit"))
        self.checkbox_restr_joint_1.setText(_translate("window", "Emement 1"))
        self.checkbox_restr_joint_2.setText(_translate("window", "Element 2"))
        self.submit_restr_point_on_segment.setText(_translate("window", "Submit"))
        self.checkbox_restr_point_on_segment_point.setText(_translate("window", "Point"))
        self.checkbox_restr_point_on_segment_line.setText(_translate("window", "Line"))
        self.submit_restr_segments_parallel.setText(_translate("window", "Submit"))
        self.checkbox_restr_segments_parallel_1.setText(_translate("window", "Line 1"))
        self.checkbox_restr_segments_parallel_2.setText(_translate("window", "Line 2"))
        self.submit_restr_segments_normal.setText(_translate("window", "Submit"))
        self.checkbox_restr_segments_normal_1.setText(_translate("window", "Line 1"))
        self.checkbox_restr_segments_normal_2.setText(_translate("window", "Line 2"))
        self.submit_restr_segment_horizontal.setText(_translate("window", "Submit"))
        self.checkbox_restr_segment_horizontal.setText(_translate("window", "Line"))
        self.submit_restr_fixed.setText(_translate("window", "Submit"))
        self.checkbox_restr_fixed.setText(_translate("window", "Element"))
        self.submit_restr_segment_length_fixed.setText(_translate("window", "Submit"))
        self.checkbox_restr_segment_length_fixed.setText(_translate("window", "Line"))
        self.submit_restr_segment_angle_fixed.setText(_translate("window", "Submit"))
        self.checkbox_restr_segment_angle_fixed_1.setText(_translate("window", "Line 1"))
        self.checkbox_restr_segment_angle_fixed_2.setText(_translate("window", "Line 2"))
        self.menuFile.setTitle(_translate("window", "File"))
        self.menu_menu.setTitle(_translate("window", "Menu"))
        self.action_new.setText(_translate("window", "New"))
        self.action_new.setShortcut(_translate("window", "Ctrl+N"))
        self.action_open.setText(_translate("window", "Open"))
        self.action_open.setShortcut(_translate("window", "Ctrl+O"))
        self.action_save.setText(_translate("window", "Save"))
        self.action_save.setShortcut(_translate("window", "Ctrl+S"))
        self.action_save_as.setText(_translate("window", "Save As"))
        self.action_save_as.setShortcut(_translate("window", "Ctrl+Shift+S"))
        self.action_close.setText(_translate("window", "Close"))
        self.action_close.setShortcut(_translate("window", "Ctrl+W"))
        self.action_undo.setText(_translate("window", "Undo"))
        self.action_undo.setShortcut(_translate("window", "Ctrl+Z"))
        self.action_redo.setText(_translate("window", "Redo"))
        self.action_redo.setShortcut(_translate("window", "Ctrl+Shift+Z"))
        self.action_show_elements_table.setText(_translate("window", "Show elements table"))
        self.action_show_elements_table.setShortcut(_translate("window", "Ctrl+T"))
        self.action_exit.setText(_translate("window", "Exit"))
        self.action_exit.setShortcut(_translate("window", "Ctrl+Q"))

